name: devfuelgaugetracker
description: "FuelGauge - Fuel tracker and performance app"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  syncfusion_flutter_charts: ^26.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
