name: fuelgauge_tracker
description: "A fuel tracking application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Removed Firebase packages
  # firebase_core: ^3.3.0
  # firebase_auth: ^5.1.2
  # cloud_firestore: ^5.1.0

  # Added Supabase package
  supabase_flutter: ^2.5.3

  provider: ^6.1.2
  shared_preferences: ^2.2.3
  syncfusion_flutter_charts: ^26.1.39
  intl: ^0.19.0
  uuid: ^4.4.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/fuelgauge_logo.png"
  min_sdk_android: 21
