// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0gChVQnDg45Ck7rX4oflQwbBgcDs1eJ0',
    appId: '1:502743878627:web:4d7119388f79935337eed6',
    messagingSenderId: '502743878627',
    projectId: 'fuel-gauge-app-3706f',
    authDomain: 'fuel-gauge-app-3706f.firebaseapp.com',
    storageBucket: 'fuel-gauge-app-3706f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7eElxyeXLXQAkoVAdSzTqmIJIXEvHudw',
    appId: '1:502743878627:android:92a7b50287562fb237eed6',
    messagingSenderId: '502743878627',
    projectId: 'fuel-gauge-app-3706f',
    storageBucket: 'fuel-gauge-app-3706f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQjeqmIigSRfGjTfA58JgNlRKPiZUnOnQ',
    appId: '1:502743878627:ios:4676d0210d3c534f37eed6',
    messagingSenderId: '502743878627',
    projectId: 'fuel-gauge-app-3706f',
    storageBucket: 'fuel-gauge-app-3706f.firebasestorage.app',
    iosBundleId: 'com.example.fuelgaugeDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQjeqmIigSRfGjTfA58JgNlRKPiZUnOnQ',
    appId: '1:502743878627:ios:4676d0210d3c534f37eed6',
    messagingSenderId: '502743878627',
    projectId: 'fuel-gauge-app-3706f',
    storageBucket: 'fuel-gauge-app-3706f.firebasestorage.app',
    iosBundleId: 'com.example.fuelgaugeDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0gChVQnDg45Ck7rX4oflQwbBgcDs1eJ0',
    appId: '1:502743878627:web:9968efe94984668337eed6',
    messagingSenderId: '502743878627',
    projectId: 'fuel-gauge-app-3706f',
    authDomain: 'fuel-gauge-app-3706f.firebaseapp.com',
    storageBucket: 'fuel-gauge-app-3706f.firebasestorage.app',
  );

}